[package]
name = "simfony-as-rust"
version = "0.1.5"
edition = "2021"
authors = ["Christian Lewe <ch_lewe@agdsn.me>"]
description = "Tools for working with Simfony as literal Rust"
license = "CC0-1.0"
repository = "https://github.com/uncomputable/simfony-as-rust"

[dependencies]
either = "1.13.0"
